### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by IdeNaoshi** [Chris911/Ask-Stack-Atom#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.9.5
**Thrown From**: [ask-stack](https://github.com/Chris911/Ask-Stack-Atom) package, v1.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/naoshi/.atom/packages/ask-stack/lib/ask-stack-result-view.coffee:174

TypeError: undefined is not a function
    at HTMLButtonElement.<anonymous> (/Users/naoshi/.atom/packages/ask-stack/lib/ask-stack-result-view.coffee:284:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:07.1.0 ask-stack:ask-question (atom-text-editor.editor)
     -1:00.8.0 core:backspace (atom-text-editor.editor.mini)
     -0:31.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "rails-snippets",
      "css-snippets",
      "javascript-snippets",
      "localization",
      "lodash-snippets",
      "rspec-snippets",
      "script",
      "script-runner",
      "symbols-tree-view",
      "wp-snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ask-stack, v1.1.0
file-icons, v1.5.4
minimap, v4.8.0

# Dev
No dev packages
```

**Comment by hazrpg** [comment]
@IdeNaoshi is this still an issue on the latest version?
