### ISSUE TITLE
ask stack tab isn't closing

### ISSUE THREAD

**Issue by mubashirbaig** [Chris911/Ask-Stack-Atom#27]

**Comment by ResidentBiscuit** [comment]
Same issue here. When attempting to close, "Uncaught TypeError: Cannot read property 'dispose' of undefined". Error thrown from tabs package, though, so might not be an issue with ask-stack.

**Comment by blobgo** [comment]
See issue https://github.com/atom/tabs/issues/183

**Comment by blobgo** [comment]
> TypeError: Cannot read property 'dispose' of undefined
  at C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:28
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
  at tabs-tab.module.exports.TabView.destroy (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\tabs\lib\tab-view.js:194:14)
  at TabBarView.module.exports.TabBarView.removeTabForItem (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:364:15)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:174:24
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:395:20)
  at Pane.module.exports.Pane.destroyItem (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:458:16)
  at HTMLDivElement.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)

**Comment by hazrpg** [comment]
Looks like this has been resolved in the newest version of Atom, is this still a problem for you? @mubashirbaig @ResidentBiscuit @blobgo

**Comment by prameshbajra** [comment]
I have the latest version but I still have this problem! Any fix available? or anything to be done manually?
The opened stack tab won't close.

**Comment by Chris911** [comment]
@Suzal3579, I am not able to reproduce the issue. I'm on 1.10.2 (latest).
