### ISSUE TITLE
Uncaught TypeError: atom.workspace.open(...).done is not a function

### ISSUE THREAD

**Issue by nucka** [Chris911/Ask-Stack-Atom#31]
[Enter steps to reproduce below:]

1. ...[ctrl-alt-a]
2. ...enter any search string
3. ...[enter]

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [ask-stack](https://github.com/Chris911/Ask-Stack-Atom) package, v2.0.0

### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /Users/####/.atom/packages/ask-stack/lib/ask-stack-view.coffee:109

TypeError: atom.workspace.open(...).done is not a function
  at AskStackView.module.exports.AskStackView.showResults (/Users/####/.atom/packages/ask-stack/lib/ask-stack-view.coffee:109:68)
  at /Users/####/.atom/packages/ask-stack/lib/ask-stack-view.coffee:104:10
  at Request._callback (/Users/####/.atom/packages/ask-stack/lib/ask-stack-api-client.coffee:46:11)
  at Request.self.callback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:123:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:1047:14)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:169:7)
  at Gunzip.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/request.js:998:12)
  at emitNone (events.js:72:20)
  at Gunzip.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
     -1:27.6.0 ask-stack:ask-question (atom-text-editor.editor.is-focused)
     -1:21.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43.9.0 ask-stack:ask-question (atom-text-editor.editor.is-focused)
  7x -0:41 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:38.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.4.0 ask-stack:ask-question (atom-text-editor.editor.is-focused)
 11x -0:13.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:07.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/####/Documents/####/git",
    "disabledPackages": [
      "editor-background"
    ],
    "themes": [
      "spacegray-dark-neue-ui",
      "spacegray-dark-neue-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.10
ask-stack, v2.0.0
atom-beautify, v0.28.16
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
clipboard-plus, v0.5.1
color-picker, v2.0.13
dash, v1.3.2
file-icons, v1.6.11
git-blame, v0.4.7
git-control, v0.4.0
highlight-selected, v0.10.1
keyboard-localization, v1.4.10
linter, v1.10.0
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-js-standard, v3.2.1
linter-php, v1.0.5
linter-ruby, v1.2.0
pigments, v0.18.1
recent-projects, v0.9.5
spacegray-dark-neue-syntax, v1.3.0
spacegray-dark-neue-ui, v1.4.0

# Dev
No dev packages
```

**Comment by Chris911** [comment]
I can't repro here. The pane with results opens just fine.

**Comment by kpfromer** [comment]
I don't know if you have fixed this issue, but I found a solution, using what I found in a [similar issue](https://github.com/yongkangchen/atom-ctags/issues/134), I changed all the references of `.done` to `.then`

**Comment by Chris911** [comment]
Thanks for the tip. As mentioned in my last comment I wasn't able to repro but if it comes back I'll check it out.

**Comment by kpfromer** [comment]
I just tested it, and it works for me.

**Comment by jeffm13** [comment]
I'm getting this problem.  You may be able to reproduce by simply opening up the source for a polymer web component, and trying to preview.
